import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: 'backlog',
    },
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
    {
      type: 'autogenerated',
      dirName: 'adr',
    },
    {
      type: 'autogenerated',
      dirName: 'backend',
    },
    {
      type: 'autogenerated',
      dirName: 'frontend',
    },
    {
      type: 'autogenerated',
      dirName: 'api',
    },
    {
      type: 'autogenerated',
      dirName: 'testing',
    },
    {
      type: 'autogenerated',
      dirName: 'review',
    },
    {
      type: 'autogenerated',
      dirName: 'devops',
    },
    {
      type: 'autogenerated',
      dirName: 'admin',
    },
    {
      type: 'autogenerated',
      dirName: 'ai',
    },
  ],
};

export default sidebars;
